from tkinter import *
import math
root = Tk()
def click(event):
    global value
    text = event.widget.cget("text")
    if text == "sin":
        value.set(math.sin(float(exp.get())))
        exp.update()
    elif text == "cos":
        value.set(math.cos(float(exp.get())))
        exp.update()
    elif text == "tan":
        value.set(math.tan(float(exp.get())))
        exp.update()
    elif text == "√":
        value.set(math.sqrt(float(exp.get())))
        exp.update()
    elif text == "ln":
        value.set(math.log(float(exp.get())))
        exp.update()
    elif text == "=":
        if value.get().isdigit():
            v = int(value.get())
        else:
            try:
                v = eval(exp.get())
                value.set(v)
                exp.update()
            except:
                value.set("Wrong expression")
                exp.update()
    elif text == "C":
        value.set("")
        exp.update()
    else:
        value.set(value.get() + text)
        exp.update()
    if text == "X":
        root.destroy()
root.title("Calculator")
root.geometry("325x392")
root.wm_iconbitmap("calculator.ico")
root.configure(bg = "skyblue")
value = StringVar()
value.set("")
exp = Entry(root, textvariable = value, bg = "grey24", font = "lucida 25 bold", fg = "white", relief = SUNKEN)
exp.pack(padx = 12, pady = 12, fill = X)
f = Frame(root, bg = "grey")
b = Button(f, text = "sin", font = "comicsansms 19 bold", padx = 18, bg = "grey", fg = "white")
b.pack()
b.bind('<Button-1>', click)
b = Button(f, text = "cos", font = "comicsansms 19 bold", padx = 14, bg = "grey", fg = "white")
b.pack()
b.bind('<Button-1>', click)
b = Button(f, text = "tan", font = "comicsansms 19 bold", padx = 17, bg = "grey", fg = "white")
b.pack()
b.bind('<Button-1>', click)
b = Button(f, text = "√", font = "comicsansms 19 bold", padx = 28, bg = "grey", fg = "white")
b.pack()
b.bind('<Button-1>', click)
b = Button(f, text = "ln", font = "comicsansms 19 bold", padx = 24, bg = "grey", fg = "white")
b.pack()
b.bind('<Button-1>', click)
b = Button(f, text = ".", font = "comicsansms 19 bold", padx = 32, bg = "grey", fg = "white")
b.pack()
b.bind('<Button-1>', click)
f.pack(side = LEFT, padx = 12)
f = Frame(root, bg = "grey")
b = Button(f, text = "9", font = "comicsansms 19 bold", padx = 14, bg = "grey", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
b = Button(f, text = "8", font = "comicsansms 19 bold", padx = 14, bg ="grey", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
b = Button(f, text = "7", font = "comicsansms 19 bold", padx = 14, bg = "grey", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
f.pack()
f = Frame(root, bg = "grey")
b = Button(f, text = "6", font = "comicsansms 19 bold", padx = 14, bg = "grey", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
b = Button(f, text = "5", font = "comicsansms 19 bold", padx = 14, bg ="grey", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
b = Button(f, text = "4", font = "comicsansms 19 bold", padx = 14, bg = "grey", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
f.pack()
f = Frame(root, bg = "grey")
b = Button(f, text = "3", font = "comicsansms 19 bold", padx = 14, bg = "grey", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
b = Button(f, text = "2", font = "comicsansms 19 bold", padx = 14, bg ="grey", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
b = Button(f, text = "1", font = "comicsansms 19 bold", padx = 14, bg = "grey", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
f.pack()
f = Frame(root, bg = "grey")
b = Button(f, text = "+", font = "comicsansms 19 bold", padx = 13.5, bg = "orange")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
b = Button(f, text = "0", font = "comicsansms 19 bold", padx = 14, bg ="grey", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
b = Button(f, text = "-", font = "comicsansms 19 bold", padx = 16.5, bg = "orange")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
f.pack()
f = Frame(root, bg = "grey")
b = Button(f, text = "*", font = "comicsansms 19 bold", padx = 16.5, bg = "orange")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
b = Button(f, text = "%", font = "comicsansms 19 bold", padx = 13, bg ="orange")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
b = Button(f, text = "/", font = "comicsansms 19 bold", padx = 16.5, bg = "orange")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
f.pack()
f = Frame(root, bg = "grey")
b = Button(f, text = "C", font = "comicsansms 19 bold", padx = 8, bg = "brown", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
b = Button(f, text = "=", font = "comicsansms 19 bold", padx = 24, bg ="blue", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
b = Button(f, text = "X", font = "comicsansms 19 bold", padx = 8, bg = "red", fg = "white")
b.pack(side = LEFT)
b.bind('<Button-1>', click)
f.pack()
root.mainloop()
